use std::collections::HashMap;
use crate::Tensor;
use crate::nn::Linear;

#[derive(crate::Module)]
pub struct InferenceModel {
    pub fc1: Linear,
    pub fc2: Linear,
}

impl InferenceModel {
    pub fn new() -> Self {
        InferenceModel {
            fc1: Linear::new(10, 5, true),
            fc2: Linear::new(5, 2, true),
        }
    }

    pub fn forward(&self, x: &Tensor) -> Tensor {
        let x1 = self.fc1.forward(x);
        let x2 = x1.relu();
        self.fc2.forward(&x2)
    }
}

// Manual implementation of StatefulModule for PoC
// In a real framework, this would be generated by a macro!
impl crate::io::StatefulModule for InferenceModel {
    fn state_dict(&self) -> HashMap<String, Tensor> {
        let mut dict = HashMap::new();
        dict.insert("fc1.weight".to_string(), self.fc1.weight.clone());
        if let Some(b) = &self.fc1.bias {
            dict.insert("fc1.bias".to_string(), b.clone());
        }
        dict.insert("fc2.weight".to_string(), self.fc2.weight.clone());
        if let Some(b) = &self.fc2.bias {
            dict.insert("fc2.bias".to_string(), b.clone());
        }
        dict
    }

    fn load_state_dict(&mut self, state_dict: HashMap<String, Tensor>) {
        if let Some(t) = state_dict.get("fc1.weight") {
            self.fc1.weight.node.borrow_mut().data = t.data();
        }
        if let Some(t) = state_dict.get("fc1.bias") {
            if let Some(b) = &self.fc1.bias {
                b.node.borrow_mut().data = t.data();
            }
        }
        if let Some(t) = state_dict.get("fc2.weight") {
            self.fc2.weight.node.borrow_mut().data = t.data();
        }
        if let Some(t) = state_dict.get("fc2.bias") {
            if let Some(b) = &self.fc2.bias {
                b.node.borrow_mut().data = t.data();
            }
        }
    }
}
